# Generated by Django 5.0.3 on 2024-04-11 13:04

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Client',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('email', models.EmailField(max_length=254)),
                ('phone', models.CharField(max_length=100)),
                ('address', models.CharField(max_length=100)),
                ('date_reg', models.DateField(auto_now_add=True)),
                ('is_active', models.BooleanField(default=True)),
            ],
        ),
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name_product', models.CharField(max_length=100)),
                ('description', models.TextField()),
                ('price', models.DecimalField(decimal_places=2, max_digits=6)),
                ('quantity', models.IntegerField(default=0)),
                ('date_add', models.DateField()),
                ('image_product', models.ImageField(null=True, upload_to='media/')),
                ('file_product', models.FileField(null=True, upload_to='files/')),
                ('is_active', models.BooleanField(default=True)),
            ],
        ),
        migrations.CreateModel(
            name='Order',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('order_total', models.DecimalField(decimal_places=2, default=0, max_digits=6)),
                ('date_ordered', models.DateField()),
                ('date_change', models.DateField(auto_now=True)),
                ('is_active', models.BooleanField(default=True)),
                ('client_store', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='myhwapp4.client')),
                ('basket_products', models.ManyToManyField(to='myhwapp4.product')),
            ],
        ),
        migrations.CreateModel(
            name='BasketProduct',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity', models.IntegerField(default=0)),
                ('order_client', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='myhwapp4.order')),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='myhwapp4.product')),
            ],
        ),
    ]
